#!/usr/bin/env bash
# Record exact versions of every external tool that touches the data, for the
# reproducibility appendix. Writes config/tool_versions.lock.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="config/tool_versions.lock"
SCORECARD_IMAGE="${SCORECARD_IMAGE:-gcr.io/openssf/scorecard:stable}"
SYFT_IMAGE="${SYFT_IMAGE:-anchore/syft:latest}"

{
  echo "# Auto-generated by scripts/tool_versions.sh — exact tool versions for reproducibility."
  echo "# (Do not edit by hand; rerun the script after changing any tool.)"
  echo ""
  echo "host_python: $(.venv/bin/python --version 2>&1 || echo 'venv missing')"
  echo "uv: $(uv --version 2>&1 || echo 'n/a')"
  echo "docker: $(docker --version 2>&1 || echo 'n/a')"
  echo "git: $(git --version 2>&1 || echo 'n/a')"
  echo ""
  echo "scorecard_image: ${SCORECARD_IMAGE}"
  echo "scorecard_version: $(docker run --rm "${SCORECARD_IMAGE}" version 2>&1 | tr '\n' ' ' | sed 's/  */ /g' || echo 'n/a')"
  echo "scorecard_digest: $(docker inspect --format='{{index .RepoDigests 0}}' "${SCORECARD_IMAGE}" 2>/dev/null || echo 'n/a')"
  echo ""
  echo "syft_image: ${SYFT_IMAGE}"
  echo "syft_version: $(docker run --rm "${SYFT_IMAGE}" version 2>&1 | grep -i version | head -1 | tr -s ' ' || echo 'n/a')"
  echo "syft_digest: $(docker inspect --format='{{index .RepoDigests 0}}' "${SYFT_IMAGE}" 2>/dev/null || echo 'n/a')"
} > "${OUT}"

echo "wrote ${OUT}:"
cat "${OUT}"
